const LinkedList = require('./linkedList')

const linkedList = new LinkedList()
linkedList.push(1)
linkedList.push(3)
linkedList.push(5)
console.log('toString: ', linkedList.toString())
linkedList.insert(4,2)
linkedList.insert(2,1)
console.log('toString: ', linkedList.toString())
console.log('indexOf3: ', linkedList.indexOf(3))
linkedList.remove(1)
console.log('toString: ', linkedList.toString())
linkedList.removeAt(2)
console.log('toString: ', linkedList.toString())
console.log('getHead: ', linkedList.getHead())
