const Queue = require('./queue')
const Deque = require('./deque')

const queue = new Queue()
console.log('isEmply: ', queue.isEmpty())

queue.enqueue('John')
queue.enqueue('Jack')
console.log('toString: ', queue.toString())

queue.enqueue('Camila')
console.log('toString: ', queue.toString())
console.log('size: ', queue.size())
console.log('isEmpty: ', queue.isEmpty())
console.log('dequeue: ', queue.dequeue())
console.log('dequeue: ', queue.dequeue())
console.log('toString: ', queue.toString())

console.log('----------------------------------------')

const deque = new Deque()
console.log('isEmpty： ', deque.isEmpty())
deque.addBack('John')
deque.addBack('Jack')
console.log('toString: ', deque.toString())
deque.addBack('Camila')
console.log('toString: ', deque.toString())
console.log('size: ', deque.size())
console.log('isEmpty： ', deque.isEmpty())
console.log('removeFront: ', deque.removeFront())
console.log('toString: ', deque.toString())
console.log('removeBack: ', deque.removeBack())
console.log('toString: ', deque.toString())
deque.addFront('John')
console.log('toString: ', deque.toString())
